### ISSUE TITLE
Colorpicker detail style

### ISSUE THREAD

**Issue by ened** [ShPakvel/bootstrap_colorpicker_rails#1]
Please see attached screenshot. The color picker is included using simple_form:

```
<%= f.input :brand_background_color, as: :colorpicker, input_html: { data: { format: 'hex' } } %>
```

![screen shot 2015-01-12 at 10 16 52](https://cloud.githubusercontent.com/assets/269860/5698249/3e23efda-9a44-11e4-83d9-2f43a9c4f954.png)

However, I noticed a few small things;
- There is a little icon on the top left (some kind of UP arrow?)
- The width of the field is not as wide as other input text fields, looks like extra CSS rules
- The label is also not as wide as other labels in a similar column

There is a css definition for `.colorpicker`, which might be the problem, as it applies for both the wrapper `<div>` and the `<input>` element itself.

**Comment by ShPakvel** [comment]
Hi Sebastian ( @ened ) !

Yep, it is a bug. :+1: 
It is because of plugin stylesheets have `.colorpicker` class styles.
And simple_form assing this class to all elements of input group according to name of input.
I've fixed it and release new version '1.0.1'. :tada:   Please check it.

Thanks,
Pavel

**Comment by ShPakvel** [comment]
I've added changes to old version as well.
Reopen this issue if it does not work for you.

**Comment by ened** [comment]
I'm using 1.0.1 - works perfectly. Thank you!
